name: Release QemuManager

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Extract version from tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      
    - name: Update version in pom.xml
      run: |
        mvn versions:set -DnewVersion=${{ steps.get_version.outputs.VERSION }}
        mvn versions:commit
        
    - name: Run tests
      run: mvn clean test
      
    - name: Build JAR with dependencies
      run: mvn clean package
      
    - name: Build executable JAR
      run: mvn clean package -P dist
      
    - name: Create Release with Assets
      uses: softprops/action-gh-release@v2
      with:
        name: QemuManager ${{ steps.get_version.outputs.VERSION }}
        body: |
          ## QemuManager Release ${{ steps.get_version.outputs.VERSION }}
          
          ### Downloads
          - **QemuManager-${{ steps.get_version.outputs.VERSION }}.jar**: Main application JAR
          - **QemuManager-${{ steps.get_version.outputs.VERSION }}-executable.jar**: Standalone executable JAR with all dependencies
          
          ### Features
          - QEMU virtual machine management
          - Disk image management with large action buttons
          - VNC integration for remote VM access
          - Configurable paths (.QemuManager directory structure)
          - Persistent VM state management
          
          ### Requirements
          - Java 11 or higher
          - QEMU installed on your system
          - VNC viewer (optional, for VM display access)
          
          ### Installation
          1. Download the JAR file
          2. Run with: `java -jar QemuManager-${{ steps.get_version.outputs.VERSION }}.jar`
          
        files: |
          target/qemu-manager-${{ steps.get_version.outputs.VERSION }}.jar
          target/qemu-manager-${{ steps.get_version.outputs.VERSION }}-jar-with-dependencies.jar
        draft: false
        prerelease: false